name: Docker Image CI

on:
  push:
    branches: [ "trampox" ]
  pull_request:
    branches: [ "trampox" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/valorao/riot-auth-client:$(date +%s)
    - name: Publish the Docker image
      run: |
        docker login -u rtrampox -p  ${{ secrets.GHCR_IO_ACTION }} ghcr.io
        docker push ghcr.io/valorao/riot-auth-client
  portainer-post:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request to Portainer
      id: request
      uses: tyrrrz/action-http-request@master
      with:
          url: https://control.rtrampox.cloud/api/stacks/webhooks/dbbc81d6-10c6-456c-b974-1d3d019a4648
          method: POST
          retry-count: 3
          retry-delay: 500

    - name: Print outputs
      run: |
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"
          echo "Headers: ${{ steps.request.outputs.headers }}"
          echo "Body: ${{ steps.request.outputs.body }}"
