name: Docker Image CI

on:
  push:
    branches: [ "trampox" ]
  pull_request:
    branches: [ "trampox" ]

jobs:
  push:
    runs-on: self-hosted
    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.MESSAGE }}
        TITLE: Github Actions
        MESSAGE: "Running a Github actions for valorao/riot-auth-client"
        LINK: https://github.com/valorao/riot-auth-client/actions
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Step
      run: echo ${GITHUB_SHA::7}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
    - name: Publish the Docker with commit short SHA as tag.
      run: |
        docker login -u rtrampox -p  ${{ secrets.GHCR_IO_ACTION }} ghcr.io
        docker push ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
        echo "Pusing valorao/riot-auth-client:${GITHUB_SHA::7}"
    - name: Re-tag Image to latest
      run: |
        docker image tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7} ghcr.io/valorao/riot-auth-client:latest
    - name: Publish the Docker with latest as tag.
      run: |
        docker push ghcr.io/valorao/riot-auth-client:latest
  portainer-post:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Send POST request to Portainer
      id: request
      uses: tyrrrz/action-http-request@master
      with:
          url: ${{ secrets.PORTAINER_POST }}
          method: POST
          retry-count: 3
          retry-delay: 500

    - name: Print outputs
      run: |
          echo "Portainer: Pulling and Updating docker Containers"
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"
          echo "Headers: ${{ steps.request.outputs.headers }}"
          echo "Body: ${{ steps.request.outputs.body }}"
  message:
    needs: portainer-post
    runs-on: self-hosted
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with: 
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        thread-id: "1239213001932931114"
        embed-title: Github Actions
        embed-description: The Github Action for valorao/riot-auth-client runned successfully.
        embed-footer-text: valorao
        embed-author-name: Actions
        embed-url: "https://github.com/valorao/riot-auth-client/actions"
        embed-author-icon-url: "https://cdn.valorao.cloud/images%2Fvalorao.png"
        avatar-url: "https://cdn.valorao.cloud/images%2F25231.png"
