name: Docker Image CI

on:
  push:
    branches: [ "trampox" ]
  pull_request:
    branches: [ "trampox" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Step
      run: echo ${GITHUB_SHA::7}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
    - name: Publish the Docker with commit short SHA as tag.
      run: |
        docker login -u rtrampox -p  ${{ secrets.GHCR_IO_ACTION }} ghcr.io
        docker push ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
        echo "Pusing valorao/riot-auth-client:${GITHUB_SHA::7}"
    - name: Re-tag Image to latest
      run: |
        docker image tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7} ghcr.io/valorao/riot-auth-client:latest
    - name: Publish the Docker with latest as tag.
      run: |
        docker push ghcr.io/valorao/riot-auth-client:latest
  portainer-post:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Send POST request to Portainer
      id: request
      uses: tyrrrz/action-http-request@master
      with:
          url: https://control.rtrampox.cloud/api/stacks/webhooks/dbbc81d6-10c6-456c-b974-1d3d019a4648
          method: POST
          retry-count: 3
          retry-delay: 500

    - name: Print outputs
      run: |
          echo "Portainer: Pulling and Updating docker Containers"
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"
          echo "Headers: ${{ steps.request.outputs.headers }}"
          echo "Body: ${{ steps.request.outputs.body }}"

name: Docker Image CI

on:
  push:
    branches: [ "trampox" ]
  pull_request:
    branches: [ "trampox" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Step
      run: echo ${GITHUB_SHA::7}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
    - name: Publish the Docker with commit short SHA as tag.
      run: |
        docker login -u rtrampox -p  ${{ secrets.GHCR_IO_ACTION }} ghcr.io
        docker push ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
        echo "Pusing valorao/riot-auth-client:${GITHUB_SHA::7}"
    - name: Re-tag Image to latest
      run: |
        docker image tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7} ghcr.io/valorao/riot-auth-client:latest
    - name: Publish the Docker with latest as tag.
      run: |
        docker push ghcr.io/valorao/riot-auth-client:latest
  portainer-post:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Send POST request to Portainer
      id: request
      uses: tyrrrz/action-http-request@master
      with:
          url: https://control.rtrampox.cloud/api/stacks/webhooks/dbbc81d6-10c6-456c-b974-1d3d019a4648
          method: POST
          retry-count: 3
          retry-delay: 500

    - name: Print outputs
      run: |
          echo "Portainer: Pulling and Updating docker Containers"
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"
          echo "Headers: ${{ steps.request.outputs.headers }}"
          echo "Body: ${{ steps.request.outputs.body }}"

  remove-package-versions:
    needs: portainer-post
    runs-on: self-hosted
    uses: smartsquaregmbh/delete-old-packages@v0.7.0
    with:
      token: ${{ secrets.GHCR_IO_ACTION }}
      organization: valorao
      type: docker
      keep: 3
      names: |
        package
