name: Docker Image CI

on:
  push:
    branches: ["trampox"]
  pull_request:
    branches: ["trampox"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Step
        run: echo ${GITHUB_SHA::7}
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
      - name: Publish the Docker with commit short SHA as tag.
        run: |
          docker login -u rtrampox -p  ${{ secrets.GHCR_IO_ACTION }} ghcr.io
          docker push ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7}
          echo "Pusing valorao/riot-auth-client:${GITHUB_SHA::7}"
      - name: Re-tag Image to latest
        run: |
          docker image tag ghcr.io/valorao/riot-auth-client:${GITHUB_SHA::7} ghcr.io/valorao/riot-auth-client:latest
      - name: Publish the Docker with latest as tag.
        run: |
          docker push ghcr.io/valorao/riot-auth-client:latest
            deployment:
  portainer_post:
    runs-on: self-hosted
    steps:
      - name: Portainer POST Docker update command
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://admin.rtrampox.cloud/api/stacks/webhooks/e0084313-702c-4258-9a4b-63db223a812b"
          method: "POST"
  vercel_purge:
    runs-on: self-hosted
    steps:
      - name: Purge Vercel cache command
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://valorao.cloud/api/revalidate?endpoint=/api/storefront"
          method: "POST"
          customHeaders: '{"x-api-key": ${{ secrets.VALORAO_API_KEY }}}'
  vercel_purge_bundles:
    runs-on: self-hosted
    steps:
      - name: Purge Vercel bundles endpoint cache command
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://valorao.cloud/api/revalidate?endpoint=/api/storefront/bundles"
          method: "POST"
          customHeaders: '{"x-api-key": ${{ secrets.VALORAO_API_KEY }}}'
  message:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          thread-id: "1239213001932931114"
          embed-title: Github Actions
          embed-description: The Github Action for valorao/riot-auth-client runned successfully.
          embed-footer-text: valorao
          embed-author-name: Actions
          embed-url: "https://github.com/valorao/riot-auth-client/actions"
          embed-author-icon-url: "https://cdn.valorao.cloud/images%2Fvalorao.png"
          avatar-url: "https://cdn.valorao.cloud/images%2F25231.png"
